### ISSUE TITLE
unist-util-visit missing in dependencies

### ISSUE THREAD

**Issue by alecmev** [remarkjs/remark-breaks#3]
This upsets Yarn 2, currently need this in `.yarnrc.yml` as a workaround:

```yml
packageExtensions:
  "remark-breaks@*":
    dependencies:
      "unist-util-visit": "*"
```

Skipping the template since this isn't an "unexpected behavior" type of bug.
